# Compiler constant folding.
print(~42)
print(2 + 3)
print(2.1 + 3.2)
print(True and False)
print('x' if True else 'y')
print('abc' + 'def' + 'ghi')
print('ABC' 'DEF' 'GHI')
print('' 'z')
print('a' '')
#print(2 'abc') # bad syntax
print(2 < 3)
print(2.1 < 3.2)
print('abc' < 'abcd')

print({3, 3.0, 4, 4.0, 'abc'})
print("3 <=> 3:", 3 <=> 3)
print("3 <=> 4:", 3 <=> 4)
print("4 <=> 3:", 4 <=> 3)
print("3 <=> 3.0:", 3 <=> 3.0)
print("3.0 <=> 3.0:", 3.0 <=> 3.0)
print("3.0 <=> 3:", 3.0 <=> 3)
print("'abc' <=> 'abc':", 'abc' <=> 'abc')
print("'abc' <=> 'abcd':", 'abc' <=> 'abcd')
print("'abcd' <=> 'abc':", 'abcd' <=> 'abc')
print("4 <=> 'abc':", 4 <=> 'abc')
print("'abc' <=> 4:", 'abc' <=> 4)
print("3.0 <=> 'abc':", 3.0 <=> 'abc')
print("'abc' <=> 3.0:", 'abc' <=> 3.0)
