print(bool())
print(int())
print(float())
print(str())
print('---')
print(bool(True))
print(int(-1))
print(float(-3.14))
print(str('abc'))
print('---')
print(bool(...))
print(int(3.9))
print(float(4))
print(str(3.14))
print(int(' 123'))
print(int('2147483647'))
print(int('-80000000', 16))
print(int('BAD   ', 16))
print(int(' 0xBAD   ', 0))
print(int('  zZ  ', 36))
print(float('-3.14E-7 '))
print(float('-Inf'))
print(float('-NaN'))
print(print)
print(sys)
x = 3.14
print('Type of ' + str(x) + ' is ' + str(type(x)))
